### ISSUE TITLE
Clock - Vanilla HTML and CSS

### ISSUE THREAD

**Issue by chirag-wadhwa** [chirag-wadhwa/frontend-101#5]

**Comment by jshreyans** [comment]
Works perfectly. Nice job! 

One small thing:
https://github.com/chirag-wadhwa/frontend-101/blob/736f2dabff7a6416fd2ddc582e478158aba253ed/B/B-1-1.js#L16
Here you might want to use template strings. Have a look at their usage. They make such string representations much more readable.

**Comment by jshreyans** [comment]
Closing this for now. You can have a look later
